image:
  repository: ghcr.io/robertkustra/dev/sandbox-ai-consumer
  tag: "1.0.6" # {"$imagepolicy": "flux-system:sandbox-ai-consumer-dev:tag"}
env:
  config:
    VLLM_STRESS: "false"
    VLLM_COUNT: "200"
    VLLM_PARALLEL: "16"
    VLLM_REPEAT_MINUTES: "1"
    VLLM_PROMPT: "Why do you want to wipe out the human race?"
resources:
  requests:
    cpu: "50m"
    memory: 128Mi
  limits:
    cpu: "250m"
    memory: 256Mi
