image:
  tag: "0.2.2" # {"$imagepolicy": "flux-system:sandbox-ai-consumer-dev:tag"}
  pullPolicy: IfNotPresent

env:
  config:
    VLLM_STRESS: "false"
    VLLM_COUNT: "100"
    VLLM_PARALLEL: "16"
    VLLM_REPEAT_MINUTES: "1"
    VLLM_PROMPT: "Tell a not-so-funny joke about computer scientists."
