image:
  tag: "0.2.0"
  pullPolicy: IfNotPresent

env:
  config:
    VLLM_STRESS: "false"
    VLLM_REPEAT_MINUTES: "1"
    VLLM_PROMPT: "Who are you? How do you feel about the future of AI in society? Write a short poem about it."
