apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: sandbox-ai-consumer-values-base
    files:
      - values.yaml=sandbox-ai-consumer-values.yaml
generatorOptions:
  disableNameSuffixHash: true