image:
  repository: ghcr.io/robertkustra/prod/sandbox-ai-consumer
  tag: "0.2.2"
  pullPolicy: IfNotPresent
env:
  config:
    VLLM_STRESS: "false"
    VLLM_COUNT: "100"
    VLLM_PARALLEL: "16"
    VLLM_REPEAT_MINUTES: "1"
    VLLM_PROMPT: "Why don't you want to wipe out humanity?"